
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 12 19:54:20 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 16;
  public static final int DIVIDE = 23;
  public static final int CONST = 35;
  public static final int NUMCONST = 25;
  public static final int NOTEQUAL = 41;
  public static final int GREATER = 44;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 33;
  public static final int LESS = 45;
  public static final int FOR = 31;
  public static final int MINUS = 20;
  public static final int RPAREN = 7;
  public static final int AND = 19;
  public static final int LESSEQUAL = 43;
  public static final int OR = 18;
  public static final int COMMA = 8;
  public static final int CLASS = 36;
  public static final int EQUALEQUAL = 40;
  public static final int PLUS = 11;
  public static final int IF = 29;
  public static final int LSQBRACE = 14;
  public static final int DOT = 21;
  public static final int ABSTRACT = 38;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 17;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int PERCENT = 24;
  public static final int BREAK = 32;
  public static final int IDENT = 28;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 42;
  public static final int LBRACE = 3;
  public static final int ELSE = 30;
  public static final int READ = 34;
  public static final int CHARCONST = 26;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 37;
  public static final int BOOLCONST = 27;
  public static final int PROG = 2;
  public static final int RSQBRACE = 15;
  public static final int PRINT = 9;
  public static final int MULTYPLY = 22;
}

